export  const PROMPTS = [
    "Keyhole",
    "Sunflower",
    "chicken",
    "Antarctica",
    "Mars",
    "Earth",
    "Alien",
    "Book",
    "Television",
    "Basketball",
    "Piano",
    "Concert",
    "Frisbee",
    "The Grinch",
    "Santa Claus",
    "Michael phelps",
    "Donald trump",
    "Joe Biden",
    "Kamala Harris",
    "Queen Elizabeth",
    "Usain Bolt",
    "Taylor Swift",
    "Tooth Fairy",
  ];